export const App_url = {
  image: {
    chat_logo: "/assets/images/chat.png",
    image_1: "/assets/images/dev-1/image-1.jpg",
    image_6: "/assets/images/dev-1/image-6.jpg",
    email: "/assets/images/email.svg",
    logo: "/assets/images/logo.png",
    sign_up_image: "/assets/images/signup-image.png",
    about_us_1: "/assets/images/about-us-1.jpg",
    contact_us: "/assets/images/contact-us.jpg",
    about_us_2: "/assets/images/about-us-2.jpg",
    ai_expert: "/assets/images/dev-1/ai-expert.png",
    local: "/assets/images/local.svg",
    ai_search: "/assets/images/ai-search.svg",
    modular: "/assets/images/modular.svg",
    building: "/assets/images/building.png",
    home: "/assets/images/dev-1/hero.png",
    your_search: "/assets/images/dev-1/manage-search.jpg",
    plan: "/assets/images/dev/plan.jpg",
    plan_3d: "/assets/images/dev-1/3d-plan.png",
    video: "/assets/images/dev/detail-video.mp4",
    school_icon: "/assets/images/school.svg",
    building_icon: "/assets/images/building.svg",
    train_icon: "/assets/images/train.svg",
    metro_icon: "/assets/images/metro.svg",
    bus_icon: "/assets/images/bus.svg",
    airport_icon: "/assets/images/airport.svg",
    away_icon: "/assets/images/away.svg",
    footer: "/assets/images/footer.svg",
    profile: "/assets/images/dev/profile.png",
  },
  link: {
    INITIAL_URL: "/",
    SIGN_IN: "/signin",
    SIGN_UP: "/signup",
    RESET_PASSWORD: "/reset-password",
    FORGET_PASSWORD: "/forget-password",
    OTP_VERIFICATION: "/otp-verification",
    PACKAGE: "/packages",
    ZECCO_FAVORITES: "/zecco-favorites",
    COSTA_DEL_SOL: "/costa-del-sol",
    PROPERTY_DETAILS: "/property",
    BLOGS: "/blogs",

    DASHBOARD: "/dashboard",
    FAVORITES: "/favorites",
    SAVED_SEARCHES: "/saved-searches",
    ACCOUNT_PACKAGE: "/account",
    AI_INSIGHTS: "/AI-insights",
    CONTACT_US: "/contact-us",
    ABOUT_ZECCO: "/about-zecco",
    PRIVACY_POLICY: "/privacy-policy",
    TERMS_CONDITION: "/terms-and-conditions",
    PROFILE: "/profile",
    MESSAGE: "/messages",
    DRAW_AREA: "/draw-area",
    NEAR_BY_LOCATIONS: "/near-by-locations",
    SELECT_AREA: "/select-area",
    PREFERENCES: "/preferences",
  },
  endpoint_url: {
    GET_AUTH_USER: "/api/user",
    USER_LOGIN: "/api/auth/signup",
    USER_SIGN_IN: "/api/auth/login",
    FORGET_PASSWORD: "/api/auth/forgot-password",
    RESET_PASSWORD: "/api/auth/reset-password",
    FORGET_PASSWORD_VERIFY_OTP: "/api/auth/verify-otp",
    VERIFY_OTP: "/api/auth/verify-otp",
    VERIFY_ACCOUNT: "/api/auth/verify-account",
    RESEND_OTP: "/resend-otp",
    LOGOUT: "/api/auth/logout",
    UPLOAD_FILE: "/api/upload",
    AI_INSIGHT: "/api/ai-insight",
    CREATE_PAYMENT: "/api/payment/create-payment",
    PAYMENT_STATUS: "/api/payment/status",
    EXPORT: "/api/payment/export",
  },
  chat_bot_url: "https://n8n.appristine.co.in/webhook/zecco/AI-Chatbot",
  chat_bot_url_main: "https://n8n.appristine.co.in/webhook/zecco/AI-Chatbot",
};

export const initialState = {
  items: [],
  totalCount: 0,
  optionList: [],
};

export const initialUserData = {
  status: "",
  user: {
    id: "",
    email: "",
    active: false,
    password: "",
    is_admin: false,
    role_permissions: "",
    api_permissions: "",
    name: "",
    emp_id: "",
    user_type: "",
    role: "",
  },
  access_token: "",
};
