export const App_url = {
  image: {
    logo: "/assets/images/logo.png",
    home: "/assets/images/dev-1/hero.png",
    expertise: "/assets/images/expertise.svg",
    building: "/assets/images/building.png",
    footer: "/assets/images/footer.svg",
    chat_logo: "/assets/images/chat.png",
    chat_logo_white : '/assets/images/chat-logo-white.png',
    sign_up_image: "/assets/images/signup-image.png",
    email: "/assets/images/email.svg",
    edit: "/assets/images/edit.svg",
    contact_us: "/assets/images/contact-us.jpg",
    about_us_1: '/assets/images/about-us-1.jpg',
    about_us_2: '/assets/images/about-us-2.jpg',
    local: '/assets/images/local.svg',
    ai_search: '/assets/images/ai-search.svg',
    modular: '/assets/images/modular.svg',
    ai_expert: '/assets/images/dev-1/ai-expert.png',
    building_icon: '/assets/images/building.svg',
    away_icon: '/assets/images/away.svg',
    cap: '/assets/images/cap.svg',
    user_cap: '/assets/images/user-cap.svg',
    school_icon: '/assets/images/school.svg',
    airport_icon: '/assets/images/airport.svg',
    bus_icon: '/assets/images/bus.svg',
    train_icon: '/assets/images/train.svg',
    metro_icon: '/assets/images/metro.svg',


    // dev images
    profile: '/assets/images/dev/profile.png',
    cds_marbella: '/assets/images/dev/cds-marbella-1.png',
    cds_malaga: '/assets/images/dev/cds-malanga.png',
    cds_fuengirola: '/assets/images/dev/cds-fuengirola.png',
    cds_Benalmádena: '/assets/images/dev/cds-Benalmádena.png',
    cds_Mijas: '/assets/images/dev/cds-Mijas.png',
    cds_Estepona: '/assets/images/dev/cds-Estepona.png',
    cds_Benahavís: '/assets/images/dev/cds-Benahavís.png',
    cds_Coín: '/assets/images/dev/cds-Coín.png',
    cds_Casares: '/assets/images/dev/cds-Casares.png',

    marbella: "/assets/images/dev/marbella.png",
    malaga: "/assets/images/dev/malaga.png",
    costa_del_sol: "/assets/images/dev/costa-del-sol.png",
    image_1: "/assets/images/dev-1/image-1.jpg",
    image_2: "/assets/images/dev-1/image-2.jpg",
    image_3: "/assets/images/dev-1/image-3.jpg",
    image_4: "/assets/images/dev-1/image-4.jpg",
    image_5: "/assets/images/dev-1/image-5.jpg",
    image_6: "/assets/images/dev-1/image-6.jpg",


    plan: "/assets/images/dev/plan.jpg",
    plan_3d: "/assets/images/dev-1/3d-plan.png",
    video: '/assets/images/dev/detail-video.mp4',

    blog_image_1: "/assets/images/dev/blog-image-1.png",
    blog_image_2: "/assets/images/dev/blog-image-2.png",
    blog_image_3: "/assets/images/dev/blog-image-3.png",

    your_search: "/assets/images/dev-1/manage-search.jpg",
  },
  link: {
    INITIAL_URL: "/",
    SIGN_IN: "/signin",
    SIGN_UP: "/signup",
    RESET_PASSWORD: "/reset-password",
    FORGET_PASSWORD: "/forget-password",
    OTP_VERIFICATION: "/otp-verification",
    PACKAGE: '/packages',
    ZECCO_FAVORITES: "/zecco-favorites",
    COSTA_DEL_SOL: '/costa-del-sol',
    PROPERTY_DETAILS: '/property',
    BLOGS: '/blogs',

    DASHBOARD: '/dashboard',
    FAVORITES: '/favorites',
    SAVED_SEARCHES: '/saved-searches',
    ACCOUNT_PACKAGE: '/account',
    AI_INSIGHTS: '/AI-insights',
    CONTACT_US: '/contact-us',
    ABOUT_ZECCO: '/about-zecco',
    PROFILE: '/profile',
    MESSAGE: '/messages',
    DRAW_AREA : '/draw-area',
    NEAR_BY_LOCATIONS : '/near-by-locations',
    SELECT_AREA : '/select-area'
  },
  endpoint_url: {
    GET_AUTH_USER : '/api/user',
    USER_LOGIN: "/api/auth/signup",
    USER_SIGN_IN: "/api/auth/login",
    FORGET_PASSWORD: "/api/auth/forgot-password",
    RESET_PASSWORD: "/api/auth/reset-password",
    FORGET_PASSWORD_VERIFY_OTP: "/api/auth/verify-otp",
    VERIFY_OTP: "/api/auth/verify-otp",
    VERIFY_ACCOUNT: "/api/auth/verify-account",
    RESEND_OTP: "/resend-otp",
    LOGOUT : '/api/auth/logout',
    UPLOAD_FILE : '/api/upload',
    AI_INSIGHT : '/api/ai-insight',
    CREATE_PAYMENT: '/api/payment/create-payment',
    PAYMENT_STATUS: '/api/payment/status',

  },
  chat_bot_url: "http://localhost:5678/webhook/zecco",
  chat_bot_url_main: "https://n8n.appristine.co.in/webhook/zecco",
};

export const initialState = {
  items: [],
  totalCount: 0,
  optionList: [],
};

export const initialUserData = {
  status: "",
  user: {
    id: "",
    email: "",
    active: false,
    password: "",
    is_admin: false,
    role_permissions: "",
    api_permissions: "",
    name: "",
    emp_id: "",
    user_type: "",
    role: "",
  },
  access_token: "",
};

