import { App_url } from "@/constant/static";
import { BreadcrumbItem } from "@/redux/modules/main/types";

const breadcrumbMap: Record<string, string> = {
  areas: "Costa del Sol areas and Cities",
  property: "Property Detail",
};

export const generateBreadcrumbs = (pathname: string): BreadcrumbItem[] => {
  const segments = pathname.split("/").filter(Boolean);

  let path = "";
  const crumbs: BreadcrumbItem[] = segments.map((segment) => {
    path += `/${segment}`;

    return {
      label:
        breadcrumbMap[segment] ||
        segment.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
      href: path,
    };
  });

  return [{ label: "Home", href: "/" }, ...crumbs];
};

export const savedSearchesData = [];

export const NAV_ITEMS = [
  {
    label: "Find Property",
    href: "/",
    breadcrumbs: [{ label: "Home", href: "/" }],
  },
  {
    label: "Costa del Sol",
    href: App_url.link.COSTA_DEL_SOL,
    breadcrumbs: [
      { label: "Home", href: "/" },
      {
        label: "Costa del Sol areas and Cities",
        href: App_url.link.COSTA_DEL_SOL,
      },
    ],
  },
  {
    label: "Zecco's Favorites",
    href: App_url.link.ZECCO_FAVORITES,
    breadcrumbs: [
      { label: "Home", href: "/" },
      { label: "Zecco's Favorites", href: App_url.link.ZECCO_FAVORITES },
    ],
  },
  {
    label: "About Zecco.es",
    href: App_url.link.ABOUT_ZECCO,
    breadcrumbs: [
      { label: "Home", href: "/" },
      { label: "About Zecco.es", href: App_url.link.ABOUT_ZECCO },
    ],
  },
  {
    label: "Packages",
    href: App_url.link.PACKAGE,
    breadcrumbs: [
      { label: "Home", href: "/" },
      { label: "Packages", href: App_url.link.PACKAGE },
    ],
  },
  {
    label: "Blogs & Insights",
    href: App_url.link.BLOGS,
    breadcrumbs: [
      { label: "Home", href: "/" },
      { label: "Blogs & Insights", href: App_url.link.BLOGS },
    ],
  },
];

export const handleProtectedRoute = (
  isLoggedIn: boolean,
  router: any,
  redirectUrl: string = App_url.link.SIGN_IN,
) => {
  if (!isLoggedIn) {
    localStorage.setItem(
      "redirect_after_login",
      window.location.pathname + window.location.search,
    );
    router.push(redirectUrl);
    return false;
  }

  return true;
};

export const formatDateMonth = (
  date: string | Date,
  locale: string = "en-US",
): string => {
  if (!date) return "";

  return new Intl.DateTimeFormat(locale, {
    month: "long",
    day: "numeric",
    year: "numeric",
  }).format(new Date(date));
};

export const formatTime = (dateString: string) => {
  return new Date(dateString).toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
    hour12: true,
  });
};

export const propertyCategoryMap: Record<number, string> = {
  1: "Apartments",
  2: "Villas",
  3: "Houses",
  4: "Country Properties",
  5: "Plots and Lands",
  6: "Commercials",
  7: "Unique Buildings",
  8: "Other",
};

export const propertyTypeMap: Record<number, string> = {
  1: "Studio",
  2: "Apartment",
  3: "Penthouse",
  4: "Town House",
  5: "Villa",
  6: "Finca",
  7: "Unique Buildings",
  8: "Cortijo",
  9: "Bungalow",
  12: "Duplex",
  13: "Semi Detached House",
  14: "Country House",
  15: "House",
  16: "Semi Detached Villa",
  17: "Ground Floor Apartment",
  18: "Loft",

  1001: "Bar",
  1002: "Building",
  1003: "Castle",
  1004: "Commercial Premises",
  1005: "Development Land",
  1006: "Discotheque",
  1008: "Golf Course",
  1009: "Golf Plot",
  1010: "Hotel",
  1011: "Hotel Plot",
  1012: "Industrial Land",
  1013: "Industrial Premises",
  1014: "Office",
  1015: "Parking",
  1016: "Restaurant",
  1017: "Shopping Centre",
  1018: "Supermarket",
  1019: "Residential Plot",
  1020: "Rustic Plot",
  1021: "Store Room",
  1022: "Boat",
  1023: "Riad",
  1026: "Unique Building",
  1027: "Palace",
  1028: "Mooring",
  1029: "Business",

  1030: "Mansion",
  1031: "Duplex Penthouse",
  1032: "Triplex",
  1033: "Estate",
  1034: "Shop",
  1035: "Office Units",
  1036: "Ground Floor Duplex",
  1037: "Investment",
  1038: "Flat",
  1039: "Chalet",
};

export const featureMap: Record<number, string> = {
  1: "Front line golf",
  2: "Front line beach",
  3: "Mountainside",
  4: "Amenities near",
  5: "Transport near",
  6: "Air conditioning",
  7: "Central heating",
  8: "Partly furnished",
  9: "Fully furnished",
  10: "Fully fitted kitchen",
  11: "Utility room",
  12: "Fireplace",
  13: "Marble floors",
  14: "Jacuzzi",
  15: "Sauna",
  16: "Satellite TV",
  17: "Basement",
  18: "Solar panels",
  19: "Guest room",
  20: "Storage room",
  21: "Gym",
  22: "Alarm",
  23: "Solarium",
  24: "Security entrance",
  25: "Double glazing",
  26: "Video entrance",
  27: "Brand new",
  28: "Dining room",
  29: "Barbecue",
  30: "Security service 24h",
  31: "Telephone",
  32: "Guest toilet",
  33: "Private terrace",
  34: "Kitchen equipped",
  35: "Living room",
  36: "Study room",
  37: "Water tank",
  38: "Parquet floors",
  39: "Wall-to-wall carpet",
  40: "Separate apartment",
  41: "Sea view",
  42: "Country view",
  43: "Mountain view",
  44: "Golf view",
  45: "Indoor pool",
  46: "Heated pool",
  47: "Underfloor heating (throughout)",
  48: "Automatic irrigation system",
  49: "Security shutters",
  50: "Smart home system",
  51: "Dolby Stereo Surround system",
  52: "Bars",
  53: "Laundry room",
  54: "Internet - Wifi",
  55: "Covered terrace",
  56: "24h Service",
  57: "Electric blinds",
  58: "Fitted wardrobes",
  59: "Gated community",
  60: "Lift",
  62: "Garden view",
  63: "Pool view",
  64: "Panoramic view",
  65: "Tennis / paddle court",
  66: "Beachside",
  67: "Cinema room",
  68: "Street view",
  69: "Doorman",
  70: "Underfloor heating (bathrooms)",
  71: "Underfloor heating (partial)",
  72: "Wine Cellar",
  73: "Steam Room",
  74: "Unfurnished",
  75: "Close to children playground",
  78: "Close to Sea/Beach",
  79: "Close to Golf",
  80: "Uncovered terrace",
  81: "Game Room",
  82: "Glass Doors",
  83: "Separate dining room",
  84: "Wooden floors",
  85: "Open plan kitchen",
  86: "Balcony",
  87: "Optional furniture",
  88: "SPA",
  89: "Turkish bath",
  90: "Wheelchair Accessible",
  91: "Excellent condition",
  92: "Good condition",
  93: "Recently Renovated/Refurbished",
  94: "Renovation Needed",
  95: "Lake view",
  96: "Urban view",
  97: "Ceiling cooling system",
  98: "Ceiling heating system",
  99: "Underfloor cooling system",
  100: "Saltwater swimming pool",
  101: "Close to shops",
  102: "Close to town",
  103: "Close to port",
  104: "Close to schools",
  105: "Surveillance cameras",
  106: "Guest apartment",
  107: "Inside Golf Resort",
  108: "Marina view",
  109: "Office room",
  110: "Pets allowed",
  111: "Individual A/C units",
  112: "Central heating by radiators",
  113: "Electric radiators",
  114: "Gas heating",
  115: "Gres floors",
  116: "Armored door",
  117: "Kitchenette",
  118: "Ground floor patio",
  119: "Partial sea views",
  120: "Well",
  121: "Porcelain floors",
  122: "Aerothermics",
  123: "Internet - Fibre optic",
  124: "Walk in closet",
  125: "Walk in closet",
  126: "Walk-in closet",
  127: "Gasoil heating",
  128: "Septic Tank",
  129: "Outdoor kitchen",
  130: "Roof terrace",
  131: "Swim jet",
  132: "Mature gardens",
  133: "Heliport",
  134: "Stone floors",
  135: "Direct sea access",
  136: "Mains electricity supply",
  137: "Mains water supply",
  138: "Stables",
  139: "Reverse Osmosis water system",
  140: "Staff accommodation",
  141: "EV charging station",
  142: "Private mooring",
  143: "Close to restaurants",
  144: "City views",
  145: "Co-Working area",
  146: "Rotating parking",
  147: "Massage Room",
  148: "Individual heating",
  152: "Porcelain Stoneware",
  153: "Cocktail bar",
  154: "Concierge Service",
  155: "Garage included in price",
  156: "Photovoltaica",
  157: "Geothermal heat pump system",
  158: "Fan coil system",
  159: "Condensation based fresh water generator",
  160: "Micro cement flooring",
  161: "Fire pit",
  162: "Panic room",
  163: "Triple glazing",
  164: "Motion detectors",
  165: "Interior (facing inner courtyard)",
  166: "Mountain Side",
  167: "Wheelchair Accesible Home",
};

export const filterList = [
  { id: 1, label: "Front line golf", value: "FrontLineGolf" },
  { id: 2, label: "Front line beach", value: "FrontLineBeach" },
  { id: 3, label: "Mountainside", value: "MountaInSide" },
  { id: 4, label: "Amenities near", value: "AmenitiesNear" },
  { id: 5, label: "Transport near", value: "TransportNear" },
  { id: 6, label: "Air conditioning", value: "Airconditioning" },
  { id: 7, label: "Central heating", value: "CentralHeating" },
  { id: 8, label: "Partly furnished", value: "PartlyFurnished" },
  { id: 9, label: "Fully furnished", value: "FullyFurnished" },
  { id: 10, label: "Fully fitted kitchen", value: "FullyFittedKitchen" },
  { id: 11, label: "Utility room", value: "UtilityRoom" },
  { id: 12, label: "Fireplace", value: "FirePlace" },
  { id: 13, label: "Marble floors", value: "MarbleFloors" },
  { id: 14, label: "Jacuzzi", value: "Jacuzzi" },
  { id: 15, label: "Sauna", value: "Sauna" },
  { id: 16, label: "Satellite TV", value: "SatelliteTV" },
  { id: 17, label: "Basement", value: "Basement" },
  { id: 18, label: "Solar panels", value: "SolarPanels" },
  { id: 19, label: "Guest room", value: "GuestRoom" },
  { id: 20, label: "Storage room", value: "StorageRoom" },
  { id: 21, label: "Gym", value: "Gym" },
  { id: 22, label: "Alarm", value: "Alarm" },
  { id: 23, label: "Solarium", value: "Solarium" },
  { id: 24, label: "Security entrance", value: "SecurityEntrance" },
  { id: 25, label: "Double glazing", value: "DoubleGlazing" },
  { id: 26, label: "Video entrance", value: "VideoEntrance" },
  { id: 27, label: "Brand new", value: "BrandNew" },
  { id: 28, label: "Dining room", value: "DiningRoom" },
  { id: 29, label: "Barbecue", value: "Barbecue" },
  { id: 30, label: "Security service 24h", value: "SecurityService24h" },
  { id: 31, label: "Telephone", value: "Telephone" },
  { id: 32, label: "Guest toilet", value: "GuestToilet" },
  { id: 33, label: "Private terrace", value: "PrivateTerrace" },
  { id: 34, label: "Kitchen equipped", value: "KitchenEquipped" },
  { id: 35, label: "Living room", value: "LivingRoom" },
  { id: 36, label: "Study room", value: "StudyRoom" },
  { id: 37, label: "Water tank", value: "WaterTank" },
  { id: 38, label: "Parquet floors", value: "ParquetFloors" },
  { id: 39, label: "Wall-to-wall carpet", value: "WallToWallCarpet" },
  { id: 40, label: "Separate apartment", value: "SeparateApartment" },
  { id: 41, label: "Sea view", value: "SeaView" },
  { id: 42, label: "Country view", value: "CountryView" },
  { id: 43, label: "Mountain view", value: "MountainView" },
  { id: 44, label: "Golf view", value: "Golfview" },
  { id: 45, label: "Indoor pool", value: "InDoorPool" },
  { id: 46, label: "Heated pool", value: "HeatedPool" },
  {
    id: 47,
    label: "Underfloor heating (throughout)",
    value: "UnderFloorHeating",
  },
  {
    id: 48,
    label: "Automatic irrigation system",
    value: "AutomaticIrrigationSystem",
  },
  { id: 49, label: "Security shutters", value: "SecurityShutters" },
  { id: 50, label: "Smart home system", value: "HomeAutomationSystem" },
  {
    id: 51,
    label: "Dolby Stereo Surround system",
    value: "DolbyStereoSurroundSystem",
  },
  { id: 52, label: "Bars", value: "Bars" },
  { id: 53, label: "Laundry room", value: "LaundryRoom" },
  { id: 54, label: "Internet - Wifi", value: "InternetWifi" },
  { id: 55, label: "Covered terrace", value: "CoveredTerrace" },
  { id: 56, label: "24h Service", value: "24hService" },
  { id: 57, label: "Electric blinds", value: "ElectricBlinds" },
  { id: 58, label: "Fitted wardrobes", value: "FittedWardrobes" },
  { id: 59, label: "Gated community", value: "GatedCommunity" },
  { id: 60, label: "Lift", value: "Lift" },
  { id: 62, label: "Garden view", value: "GardenView" },
  { id: 63, label: "Pool view", value: "PoolView" },
  { id: 64, label: "Panoramic view", value: "PanoramicView" },
  { id: 65, label: "Tennis / paddle court", value: "TennisPaddleCourt" },
  { id: 66, label: "Beachside", value: "Beachside" },
  { id: 67, label: "Cinema room", value: "CinemaRoom" },
  { id: 68, label: "Street view", value: "StreetView" },
  { id: 69, label: "Doorman", value: "Doorman" },
  {
    id: 70,
    label: "Underfloor heating (bathrooms)",
    value: "UnderfloorHheatingBathrooms",
  },
  {
    id: 71,
    label: "Underfloor heating (partial)",
    value: "UnderfloorHeatingPartial",
  },
  { id: 72, label: "Wine Cellar", value: "WineCellar" },
  { id: 73, label: "Steam Room", value: "SteamRoom" },
  { id: 74, label: "Unfurnished", value: "Unfurnished" },
  {
    id: 75,
    label: "Close to children playground",
    value: "CloseToChildrenPlayground",
  },
  { id: 78, label: "Close to Sea/Beach", value: "CloseToSeaBeach" },
  { id: 79, label: "Close to Golf", value: "CloseToGolf" },
  { id: 80, label: "Uncovered terrace", value: "UncoveredTerrace" },
  { id: 81, label: "Game Room", value: "GameRoom" },
  { id: 82, label: "Glass Doors", value: "GlassDoors" },
  { id: 83, label: "Separate dining room", value: "SeparateDiningRoom" },
  { id: 84, label: "Wooden floors", value: "WoodenFloors" },
  { id: 85, label: "Open plan kitchen", value: "OpenPlanKitchen" },
  { id: 86, label: "Balcony", value: "Balcony" },
  { id: 87, label: "Optional furniture", value: "OptionalFurniture" },
  { id: 88, label: "SPA", value: "SPA" },
  { id: 89, label: "Turkish bath", value: "TurkishBath" },
  { id: 90, label: "Wheelchair Accessible", value: "WheelchairAccessible" },
  { id: 91, label: "Excellent condition", value: "ExcellentCondition" },
  { id: 92, label: "Good condition", value: "GoodCondition" },
  {
    id: 93,
    label: "Recently Renovated/Refurbished",
    value: "RecentlyRenovatedRefurbished",
  },
  { id: 94, label: "Renovation Needed", value: "RenovationNeeded" },
  { id: 95, label: "Lake view", value: "LakeView" },
  { id: 96, label: "Urban view", value: "UrbanView" },
  { id: 97, label: "Ceiling cooling system", value: "CeilingCoolingSystem" },
  { id: 98, label: "Ceiling heating system", value: "CeilingHeatingSystem" },
  {
    id: 99,
    label: "Underfloor cooling system",
    value: "UnderfloorCoolingSystem",
  },
  { id: 100, label: "Saltwater swimming pool", value: "SaltwaterSwimmingPool" },
  { id: 101, label: "Close to shops", value: "CloseToShops" },
  { id: 102, label: "Close to town", value: "CloseToTown" },
  { id: 103, label: "Close to port", value: "CloseToPort" },
  { id: 104, label: "Close to schools", value: "CloseToSchools" },
  { id: 105, label: "Surveillance cameras", value: "SurveillanceCameras" },
  { id: 106, label: "Guest apartment", value: "GuestApartment" },
  { id: 107, label: "Inside Golf Resort", value: "InsideGolfResort" },
  { id: 108, label: "Marina view", value: "MarinaView" },
  { id: 109, label: "Office room", value: "OfficeRoom" },
  { id: 110, label: "Pets allowed", value: "PetsAllowed" },
  { id: 111, label: "Individual A/C units", value: "IndividualUnitsAC" },
  {
    id: 112,
    label: "Central heating by radiators",
    value: "CentralHeatingByRadiators",
  },
  { id: 113, label: "Electric radiators", value: "ElectricRadiators" },
  { id: 114, label: "Gas heating", value: "GasHeating" },
  { id: 115, label: "Gres floors", value: "GresFloors" },
  { id: 116, label: "Armored door", value: "ArmoredDoor" },
  { id: 117, label: "Kitchenette", value: "kitchenette" },
  { id: 118, label: "Ground floor patio", value: "GroundFloorPatio" },
  { id: 119, label: "Partial sea views", value: "PartialSeaViews" },
  { id: 120, label: "Well", value: "Well" },
  { id: 121, label: "Porcelain floors", value: "PorcelainFloors" },
  { id: 122, label: "Aerothermics", value: "Aerothermics" },
  { id: 123, label: "Internet - Fibre optic", value: "InternetFibre" },
  { id: 124, label: "Walk in closet", value: "Walk in closet" },
  { id: 125, label: "Walk in closet", value: "Walk in closet" },
  { id: 126, label: "Walk-in closet", value: "WalkinCloset" },
  { id: 127, label: "Gasoil heating", value: "GasoilHeating" },
  { id: 128, label: "Septic Tank", value: "SepticTank" },
  { id: 129, label: "Outdoor kitchen", value: "OutdoorKitchen" },
  { id: 130, label: "Roof terrace", value: "RoofTerrace" },
  { id: 131, label: "Swim jet", value: "SwimJet" },
  { id: 132, label: "Mature gardens", value: "MatureJardens" },
  { id: 133, label: "Heliport", value: "Heliport" },
  { id: 134, label: "Stone floors", value: "StoneFloors" },
  { id: 135, label: "Direct sea access", value: "DirectSeaAccess" },
  {
    id: 136,
    label: "Mains electricity supply",
    value: "MainsElectricitySupply",
  },
  { id: 137, label: "Mains water supply", value: "MainsWaterSupply" },
  { id: 138, label: "Stables", value: "Stables" },
  {
    id: 139,
    label: "Reverse Osmosis water system",
    value: "ReverseOsmosisWaterSystem",
  },
  { id: 140, label: "Staff accommodation", value: "StaffAccommodation" },
  { id: 141, label: "EV charging station", value: "EVChargingStation" },
  { id: 142, label: "Private mooring", value: "PrivateMooring" },
  { id: 143, label: "Close to restaurants", value: "CloseToRestaurants" },
  { id: 144, label: "City views", value: "CityViews" },
  { id: 145, label: "Co-Working area", value: "CoWorkingSpace" },
  { id: 146, label: "Rotating parking", value: "RotatingParking" },
  { id: 147, label: "Massage Room", value: "MassageRoom" },
  { id: 148, label: "Individual heating", value: "Individualheating" },
  { id: 152, label: "Porcelain Stoneware", value: "PorcelainStoneware" },
  { id: 153, label: "Cocktail bar", value: "CocktailBar" },
  { id: 154, label: "Concierge Service", value: "ConciergeService" },
  {
    id: 155,
    label: "Garage included in price",
    value: "GarageIncludedInPrice",
  },
  { id: 156, label: "Photovoltaica", value: "photovoltaica" },
  {
    id: 157,
    label: "Geothermal heat pump system",
    value: "GeothermalHeatPumpSystem",
  },
  { id: 158, label: "Fan coil system", value: "FanCoilSystem" },
  {
    id: 159,
    label: "Condensation based fresh water generator",
    value: "CondensationBasedFreshWaterGenerator",
  },
  { id: 160, label: "Micro cement flooring", value: "MicroCementFlooring" },
  { id: 161, label: "Fire pit", value: "FirePit" },
  { id: 162, label: "Panic room", value: "PanicRoom" },
  { id: 163, label: "Triple glazing", value: "TripleGlazing" },
  { id: 164, label: "Motion detectors", value: "MotionDetectors" },
  {
    id: 165,
    label: "Interior (facing inner courtyard)",
    value: "InteriorFacingInnerCourtyard",
  },
  { id: 166, label: "Mountain Side", value: "sidemountain" },
  {
    id: 167,
    label: "Wheelchair Accesible Home",
    value: "wheelchairAccesibleHome",
  },
];

export const camelCase = (text: string = "") => {
  return text
    .toLowerCase()
    .split(" ")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
};

export const citySlug = (city_name: any) => {
  return city_name?.trim().toLowerCase().replace(/\s+/g, "-");
};
