import { IFeature } from "@/redux/modules/main/types";
import {
  Accessibility,
  Baby,
  BadgeCheck,
  BadgeDollarSign,
  BadgeInfo,
  BadgePercent,
  Banknote,
  Bath,
  Bed,
  Blinds,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Bus,
  Cable,
  Camera,
  Car,
  CarFront,
  CheckCircle,
  ChefHat,
  Church,
  Cigarette,
  CircleDashed,
  CircleOff,
  Clapperboard,
  ClipboardList,
  Coffee,
  Compass,
  ConciergeBell,
  CookingPot,
  CookingPotIcon,
  Cpu,
  DoorOpen,
  Droplets,
  Dumbbell,
  Eye,
  Fence,
  FileCheck,
  FileSearch,
  FileText,
  FileX,
  Fish,
  Flag,
  Flame,
  FlameKindling,
  Flower2,
  Gamepad2,
  Gem,
  GlassWater,
  Grid2X2,
  Hammer,
  Hand,
  HeartHandshake,
  Heater,
  Home,
  Hospital,
  Hotel,
  House,
  Landmark,
  Leaf,
  Loader,
  LucideIcon,
  MapPin,
  Map,
  Mountain,
  Package,
  Palmtree,
  PanelsTopLeft,
  ParkingCircle,
  PawPrint,
  Phone,
  Plane,
  RefreshCcw,
  RotateCcw,
  Scan,
  School,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  Shirt,
  ShoppingBag,
  Siren,
  Snowflake,
  Sofa,
  SofaIcon,
  Sparkles,
  Sprout,
  SquareStack,
  Sun,
  SunMedium,
  Tent,
  TentTree,
  Thermometer,
  Toilet,
  Trees,
  TreesIcon,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Tv,
  UserCheck,
  Users,
  Utensils,
  Video,
  View,
  Volleyball,
  Volume2,
  Wallet,
  Warehouse,
  Waves,
  WavesLadder,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Zap,
  SnowflakeIcon,
} from "lucide-react";
import { useState } from "react";

export const iconMap: Record<string, LucideIcon> = {
  FrontLineGolf: Waves,
  FrontLineBeach: Waves,
  MountaInSide: Mountain,
  AmenitiesNear: MapPin,
  TransportNear: Bus,
  Airconditioning: Snowflake,
  CentralHeating: Flame,
  PartlyFurnished: Sofa,
  FullyFurnished: Sofa,
  FullyFittedKitchen: ChefHat,
  UtilityRoom: Warehouse,
  MarbleFloors: Gem,
  MarbleFlooring: Gem,
  Jacuzzi: Bath,
  Sauna: WavesLadder,
  SatelliteTV: Tv,
  Basement: Building2,
  SolarPanels: Sun,
  GuestRoom: Bed,
  StorageRoom: Package,
  Gym: Dumbbell,
  Alarm: ShieldAlert,
  Solarium: SunMedium,
  SecurityEntrance: ShieldCheck,
  DoubleGlazing: SquareStack,
  VideoEntrance: Video,
  BrandNew: Sparkles,
  DiningRoom: Utensils,
  Barbecue: CookingPot,
  SecurityService24h: ShieldCheck,
  Telephone: Phone,
  GuestToilet: Toilet,
  PrivateTerrace: TentTree,
  KitchenEquipped: ChefHat,
  LivingRoom: Home,
  StudyRoom: BookOpen,
  WaterTank: Droplets,
  ParquetFloors: Trees,
  SeparateApartment: Building2,
  SeaView: Waves,
  CountryView: Trees,
  Country: Trees,
  MountainView: Mountain,
  Golfview: Eye,
  InDoorPool: WavesLadder,
  HeatedPool: Thermometer,
  UnderFloorHeating: Flame,
  AutomaticIrrigationSystem: Sprout,
  SecurityShutters: Blinds,
  HomeAutomationSystem: Cpu,
  DolbyStereoSurroundSystem: Volume2,
  Bars: Wine,
  LaundryRoom: Shirt,
  InternetWifi: Wifi,
  CoveredTerrace: Tent,
  "24hService": ConciergeBell,
  ElectricBlinds: Zap,
  FittedWardrobes: DoorOpen,
  GatedCommunity: Fence,
  GardenView: Flower2,
  PoolView: WavesLadder,
  PanoramicView: View,
  TennisPaddleCourt: Volleyball,
  Beachside: Waves,
  CinemaRoom: Clapperboard,
  StreetView: Eye,
  Doorman: UserCheck,
  UnderfloorHheatingBathrooms: Heater,
  UnderfloorHeatingPartial: Heater,
  WineCellar: Wine,
  SteamRoom: WavesLadder,
  Unfurnished: CircleOff,
  CloseToChildrenPlayground: TentTree,
  CloseToSeaBeach: Waves,
  CloseToGolf: Flag,
  UncoveredTerrace: Tent,
  GameRoom: Gamepad2,
  GlassDoors: PanelsTopLeft,
  SeparateDiningRoom: Utensils,
  WoodenFloors: Trees,
  OpenPlanKitchen: CookingPotIcon,
  Balcony: Building,
  OptionalFurniture: SofaIcon,
  SPA: Bath,
  TurkishBath: Bath,
  WheelchairAccessible: Accessibility,
  ExcellentCondition: BadgeCheck,
  GoodCondition: BadgeCheck,
  RecentlyRenovatedRefurbished: Wrench,
  RenovationNeeded: Hammer,
  LakeView: GlassWater,
  UrbanView: Building,
  CeilingCoolingSystem: Snowflake,
  CeilingHeatingSystem: Flame,
  UnderfloorCoolingSystem: Snowflake,
  SaltwaterSwimmingPool: Waves,
  CloseToShops: ShoppingBag,
  CloseToTown: Building2,
  CloseToPort: Ship,
  CloseToSchools: School,
  SurveillanceCameras: Camera,
  GuestApartment: Building2,
  InsideGolfResort: Flag,
  MarinaView: Ship,
  OfficeRoom: Briefcase,
  PetsAllowed: PawPrint,
  IndividualUnitsAC: Snowflake,
  GasHeating: Flame,
  GresFloors: Grid2X2,
  ArmoredDoor: Shield,
  kitchenette: Coffee,
  GroundFloorPatio: Tent,
  PartialSeaViews: Waves,
  Well: Droplets,
  PorcelainFloors: Grid2X2,
  Aerothermics: Wind,
  InternetFibre: Wifi,
  WalkinCloset: DoorOpen,
  GasoilHeating: Flame,
  SepticTank: Droplets,
  OutdoorKitchen: CookingPot,
  RoofTerrace: TentTree,
  SwimJet: Fish,
  MatureJardens: TreesIcon,
  Heliport: Plane,
  StoneFloors: Gem,
  DirectSeaAccess: Waves,
  MainsElectricitySupply: Cable,
  MainsWaterSupply: Droplets,
  Stables: Home,
  ReverseOsmosisWaterSystem: Droplets,
  StaffAccommodation: Users,
  EVChargingStation: Car,
  PrivateMooring: Ship,
  CloseToRestaurants: Utensils,
  CityViews: Building,
  CoWorkingSpace: Briefcase,
  RotatingParking: RotateCcw,
  MassageRoom: Hand,
  Individualheating: Flame,
  PorcelainStoneware: Gem,
  CocktailBar: Wine,
  ConciergeService: ConciergeBell,
  GarageIncludedInPrice: ParkingCircle,
  photovoltaicа: Sun,
  GeothermalHeatPumpSystem: Flame,
  FanCoilSystem: Wind,
  CondensationBasedFreshWaterGenerator: Droplets,
  MicroCementFlooring: Hammer,
  FirePit: FlameKindling,
  FirePlace: FlameKindling,
  PanicRoom: ShieldAlert,
  TripleGlazing: SquareStack,
  MotionDetectors: Siren,
  InteriorFacingInnerCourtyard: Home,
  sidemountain: Mountain,
  wheelchairAccesibleHome: Accessibility,
  Town: Building2,
  Suburban: House,
  CommercialArea: Briefcase,
  Village: Home,
  MountainPueblo: Mountain,
  CloseToSkiing: SnowflakeIcon,
  CloseToForest: Trees,
  Marina: Ship,
  CloseToMarina: Ship,
  NorthFacing: Compass,
  NorthEastOrientation: Compass,
  EastFacing: Compass,
  SouthEastOrientation: Compass,
  SouthFacing: Compass,
  SouthWestOrientation: Compass,
  WestFacing: Compass,
  NorthWestOrientation: Compass,
  FairCondition: BadgeInfo,
  CommunalPool: WavesLadder,
  PrivatePool: Waves,
  RoomForPool: Waves,
  ChildrensPool: Baby,
  PreInstalledAC: Snowflake,
  HotAC: Flame,
  ColdAC: Snowflake,
  BeachViews: Waves,
  PortViews: Ship,
  CourtyardViews: Building,
  SkiViews: Mountain,
  ForestViews: Trees,
  NearTransport: Bus,
  PaddleTennis: Volleyball,
  TennisCourt: Trophy,
  GuestHouse: House,
  EnsuiteBathroom: Bath,
  DisabledAccess: Accessibility,
  Domotics: Cpu,
  Reception24Hour: ConciergeBell,
  RestaurantOnSite: Utensils,
  CarHireFacility: Car,
  CourtesyBus: Bus,
  DayCare: Baby,
  NearMosque: Landmark,
  NearChurch: Church,
  FiberOptic: Wifi,
  wifi: Wifi,
  PartFurnished: Sofa,
  NotFurnished: CircleOff,
  PartiallyFittedKitchen: ChefHat,
  NotFittedKitchen: CookingPot,
  KitchenLounge: CookingPot,
  CommunalGarden: Flower2,
  PrivateGarden: Trees,
  LandscapedGarden: Sprout,
  EasyMaintenanceGarden: Leaf,
  EntryPhone: Phone,
  Security24Hour: ShieldCheck,
  Safe: Shield,
  UndergroundParking: ParkingCircle,
  Garage: CarFront,
  CoveredParking: ParkingCircle,
  OpenParking: ParkingCircle,
  StreetParking: ParkingCircle,
  MultipleParkingSpaces: ParkingCircle,
  CommunalParking: ParkingCircle,
  PrivateParking: ParkingCircle,
  Electricity: Cable,
  DrinkableWater: Droplets,
  Gas: Flame,
  PhotovoltaicSolarPanels: Sun,
  SolarWaterHeating: SunMedium,
  Bargain: BadgeDollarSign,
  Cheap: Wallet,
  Distressed: TriangleAlert,
  HolidayHomes: Palmtree,
  Investment: TrendingUp,
  Luxury: Gem,
  OffPlan: ClipboardList,
  Reduced: BadgePercent,
  Repossession: Banknote,
  Resale: RefreshCcw,
  WithPlanningPermission: FileCheck,
  Contemporary: Sparkles,
  NewDevelopment: Building,
  Plot: Map,
  WithLicense: FileCheck,
  WithoutLicense: FileX,
  Residential: House,
  Commercial: Briefcase,
  Project: ClipboardList,
  Rustic: Trees,
  Urbanised: Building2,
  FullyApproved: BadgeCheck,
  NotStarted: CircleDashed,
  PartiallyComplete: Loader,
  FullyComplete: CheckCircle,
  Hotel: Hotel,
  Hostel: Bed,
  BedAndBreakfast: Coffee,
  Restaurant: Utensils,
  Shop: ShoppingBag,
  Office: Briefcase,
  Apartments: Building2,
  TownHouses: House,
  Villas: Home,
  NursingHome: HeartHandshake,
  Hospital: Hospital,
  School: School,
  SportsCentre: Dumbbell,
  EquestrianCentre: Scan,
  GolfCourse: Flag,
  GarageSpace: ParkingCircle,
  Warehouse: Warehouse,
  Leasehold: FileText,
  BankGuaranteeRequired: Landmark,
  ReferencesRequired: FileSearch,
  SmokingAllowed: Cigarette,
};

const formatText = (text: string) => {
  return text.replace(/([A-Z])/g, " $1").trim();
};

export default function BasicFeatures(features: { features: IFeature[] }) {
  const [showAllFeatures, setShowAllFeatures] = useState(false);

  const featureList = features?.features || [];

  const visibleFeatures = showAllFeatures
    ? featureList
    : featureList.slice(0, 12);

  const normalizeKey = (text: string) =>
    text?.toLowerCase().replace(/[^a-z0-9]/g, "");

  const lowerCaseIconMap = Object.keys(iconMap).reduce(
    (acc, key) => {
      acc[key.toLowerCase()] = iconMap[key];
      return acc;
    },
    {} as Record<string, LucideIcon>,
  );

  return (
    <div className="mb-8">
      <h3 className="text-xl font-bold font-manrope text-heading_text_color mb-4">
        Basic Features
      </h3>

      <div className="w-full bg-white border border-gray-100 rounded-2xl px-6 py-5 shadow-sm">
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-y-2 gap-x-2">
          {visibleFeatures?.map((feature, index) => {
            const Icon = lowerCaseIconMap[normalizeKey(feature?.name)] || Scan;
            return (
              <>
                <Feature
                  key={index}
                  icon={<Icon className="w-5 h-5 text-[#94A3B8]" />}
                  text={formatText(feature?.name)}
                />
              </>
            );
          })}
        </div>
        {featureList?.length > 10 && (
          <button
            onClick={() => setShowAllFeatures(!showAllFeatures)}
            className="mt-4 w-full text-center text-blue-600 font-medium font-manrope hover:underline"
          >
            {showAllFeatures ? "Show Less" : "More"}
          </button>
        )}
      </div>
    </div>
  );
}

/* Reusable row */
function Feature({ icon, text }: { icon: React.ReactNode; text: string }) {
  return (
    <div className="flex items-center gap-3">
      <div className="w-9 h-9 flex items-center justify-center rounded-lg text-[#94A3B8] ">
        {icon}
      </div>
      <p className="text-[15px] font-manrope font-medium text-[#334155]">
        {text}
      </p>
    </div>
  );
}
